// Knowledge-base-grounded explanations shown in UI tooltips.
export const G: Record<string, string> = {
  value: "How cheap the stock is versus its intrinsic worth — built from earnings yield, P/E & PEG vs peers, and a DCF margin of safety (Graham). High = trading well below conservative fair value. A low price alone isn't enough; it must be cheap relative to quality, or it's a value trap.",
  quality: "Business durability and profitability: return on invested capital vs cost of capital, stable/high margins, low debt, and a moat (brand, switching costs, network, scale). AQR's 'Buffett's Alpha' shows Buffett's record was largely quality + safety + a fair price. Note: the app's return figure uses Finnhub's return-on-investment, falling back to ROE — a proxy for true ROIC — so on highly-leveraged names the moat credit is capped, since ROE can look strong purely on borrowed money.",
  momentum: "Recent relative strength — typically the 12-month return excluding the last month, plus price vs its trend. A real but shrunken factor (Jegadeesh-Titman): it works, but is volatile and prone to sharp reversals.",
  safety: "How badly the position can hurt you: low beta and volatility, shallow drawdowns, stable earnings. 'Betting against beta' shows safer, lower-beta stocks have historically delivered better risk-adjusted returns.",
  composite: "A weighted blend of the four pillars using your bucket's weights (set on the Rules tab). It's a decision aid, not a verdict — the pillar inputs are judgments, so treat the number as directional.",
  verdict: "Maps the composite SCORE to a band — Strong (≥ strong threshold), Watch (≥ watch threshold), else Pass/Review. It reflects fundamentals only, not price risk. A red 'Stop hit' or amber 'Near stop' chip appears here when this holding's trailing stop is breached or within 5% — a separate exit signal that can override a strong score. Thresholds and per-bucket stops are set on the Rules tab.",
  price: "Latest available price (last close, refreshed on demand from Finnhub; Amsterdam-listed names via Yahoo), shown in the holding's native currency.",
  buy_target: "The price you want to buy at. The Signal turns green when the live price drops to or below it. Set it from your fair-value estimate minus a margin of safety (per bucket).",
  signal: "Actionable status: how far price sits above your Buy target (or '▼ buy reached' once hit), combined with the latest score verdict. Sort by it to surface what's closest to a buy.",
  thesis: "Your free-text investment case for watching this name — why it's interesting, the catalyst, what you're waiting for. Distinct from the structured Reasons tags.",
  reasons: "Structured tags for WHY you're watching (Value, Quality, Growth, Momentum, Diversifier, Income, Catalyst, Turnaround, Theme). Each maps to a knowledge-base theory so the watchlist stays filterable.",
  weight: "This holding's share of total portfolio value (in EUR). Turns red when a single non-index name exceeds your single-name cap — your cue to trim. Concentration is the one risk that can permanently impair you.",
  ret: "Price change versus your entry price (green = gain, red = loss). It's return-since-purchase, not a quality signal — don't anchor buy/sell decisions to it (behavioural finance).",
  bucket: "The role a holding plays. Core-Index + Core-Quality form the diversified core; Growth + Speculative are size-capped satellites; Conviction (stored as “Concentrated”) = a legacy oversized position (NOW). Core-satellite keeps active risk contained to the satellites.",
  ticker: "The stock symbol. Click it anywhere in the app to open its detail panel with the holding info and its score history over time.",
  date: "When the score was saved. Every score is timestamped so you can compare how a name's score drifts over time.",
  single_name_cap: "Maximum % any single stock (excluding the broad index) may be. Above it, trim back toward target.",
  speculative_cap: "Maximum % the whole speculative bucket may be. These are option-like bets that can go to zero, so the total is hard-capped and each ticket kept tiny.",
  targets: "Your intended % per bucket. New money goes to the most-underweight bucket first (built-in buy-low). The weights should sum to ~100%.",
  strong_threshold: "Composite at or above this = 'Strong candidate'.",
  watch_threshold: "Composite at or above this (but below Strong) = 'Watchlist'; below it = 'Pass/Review'.",
  weights: "How much each pillar counts toward the composite. Tune per how YOU invest — quality buckets weight Quality & Safety more; growth buckets weight Momentum & Growth more. Should sum to 100.",
  eur_usd: "EUR/USD rate used to convert USD holdings into euros so weights are comparable across currencies.",
  total_value: "Current market value of all holdings, converted to EUR.",
  cost_basis: "Total you paid (entry price × shares), in EUR.",
  unrealised_pl: "Current value minus cost basis — paper gain/loss, before tax and fees.",
  positions: "Number of distinct holdings.",
  allocation: "Your current % per bucket vs the target you set on the Rules tab. Big gaps are rebalancing candidates.",
  alerts: "Automatic rule checks: single-name cap breaches, speculative-cap breaches, and 5/25 allocation drift (rebalance when a bucket drifts 5 points absolute, or a holding 25% relative). Your portfolio's standing to-do list.",
  shares: "Number of shares you currently hold in this position.",
  note: "Free-text context saved with the score — typically the scoring method and data source, plus any remark.",
  tx_action: "Transaction type — Buy, Sell, dividend, split, etc. — as imported from your broker feed or entered manually.",
  tx_quantity: "Number of shares transacted. A Sell reduces the position; a Buy adds to it.",
  tx_price: "Execution price per share for this transaction, in the trade's own currency.",
  fees: "Transaction costs (commission + exchange fees) for this trade, converted to EUR.",
  tx_total: "Total cash effect of the transaction in EUR, fees included.",
  source: "Where this transaction came from — an imported broker file (e.g. DeGiro) or a manual entry.",
}
